apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        resources:
          limits:
            memory: "512Mi"  # Set the maximum memory limit for the container
          requests:
            memory: "256Mi"  # Set the initial memory request for the container
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: your_password_here
          - name: MYSQL_DATABASE
            value: your_database_name
          - name: MYSQL_USER
            value: your_mysql_user
          - name: MYSQL_PASSWORD
            value: your_mysql_password
        ports:
        - containerPort: 3306
